name: CI & CD

on:
  push:
    branches:
      - feature/use-internal-database #testing
  # Trigger the workflow on pushes to the main branch, including PR merges:
  # push:
  #   branches:
  #     - main

# Generate a GitHub token that can be exchanged with Google Cloud - see
# https://github.com/google-github-actions/auth/tree/v0.6.0#setting-up-workload-identity-federation
permissions:
  contents: read
  id-token: write
  deployments: write

jobs:
  test-and-build:
    name: Integration
    uses: ./.github/workflows/test-and-build.yml
    secrets: inherit
