name: CI & CD

on:
  # Trigger the workflow on pushes to the main branch, including PR merges:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  deployments: write

jobs:
  build-and-push-to-gcp:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: sepomex
      PROJECT_ID: sepomex-365521

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        workload_identity_provider: projects/582875546495/locations/global/workloadIdentityPools/github-pool/providers/github-provider
        service_account: github-actions@sepomex-365521.iam.gserviceaccount.com

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.6.0

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

    - name: Push Docker Image to Artifact Registry
      env:
        GIT_TAG: v0.1.0
      run: |-
        docker tag $IMAGE_NAME:latest us-central1-docker.pkg.dev/$PROJECT_ID/icalialabs-sepomex/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest us-central1-docker.pkg.dev/$PROJECT_ID/icalialabs-sepomex/$IMAGE_NAME:$GIT_TAG
        docker push us-central1-docker.pkg.dev/$PROJECT_ID/icalialabs-sepomex/$IMAGE_NAME:latest
        docker push us-central1-docker.pkg.dev/$PROJECT_ID/icalialabs-sepomex/$IMAGE_NAME:$GIT_TAG
